server:
  port: 8081

spring:
  application:
    name: accounts-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/accounts_db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: false
    baseline-on-migrate: true

http-sms:
  api-key: ${HTTP_SMS_KEY:PLACEHOLDER_KEY}
  phone-number: ${HTTP_SMS_PHONE:PLACEHOLDER_PHONE}

jwt:
  secret: ${JWT_SECRET:secret_key_placeholder_for_nextbank_digital_platform_2024}
  expiration: 86400000 # 24 hours
